### ISSUE TITLE
Feature Request: -onclick for pie slices.

### ISSUE THREAD

**Issue by progmatic73** [psDevUK/New-UDPieChart3D#1]
Is it possible to have an -Onclick/-Onchange param for the control. 
So that if a pie slice is clicked it can trigger a sync-udelement. 
Then it can be wired up to display the clicked slice values in a table.

Thank you for all the great work you've been doing.

**Comment by psDevUK** [comment]
Hello @progmatic73 thanks for taking the time to download and use this component on a dashboard. I would have to read the documentation to see if I can implement...there was actually the google table I did but didn't release it just yet....maybe I can display that when clicked? I will look into though

**Comment by psDevUK** [comment]
Hello @progmatic73 I did have a look through the options and couldn't find an onclick I could bind to.  I did however release the google table chart which you would put along-side or below the pie chart, to show same data but in diff format....?

**Comment by psDevUK** [comment]
Ok this is the best link I can find:- https://developers.google.com/chart/interactive/docs/reference#visgetselection sadly I am no JS ninja, so if you can figure this out, then please reopen this issue with that solution, this is beyond my current JS knowledge I am afraid. But this looks like the best possible option to get the data when it is clicked.

**Comment by progmatic73** [comment]
@psDevUK Thanks for checking.  I'll reopen/pr if I can find something.
